/* ================================================================
   data.js — ข้อมูลตั้งต้นของระบบ (Seed data)
   ดึงมาจาก Google Sheet ต้นฉบับของโรงเรียน (ชีต "29.+สถิติผลการเรียน--2569_1--")
   ใช้เป็นข้อมูลสำรอง (fallback) เมื่อยังไม่ได้เชื่อมต่อ Backend จริง
   หรือเมื่อ Backend เชื่อมต่อไม่ได้ชั่วคราว
   ================================================================ */

// รายวิชา/ครูผู้สอน ทั้งหมด (จากชีตต้นฉบับ ภาคเรียนที่ 1 ปีการศึกษา 2569)
// โครงสร้าง: { level, groupNo, year, term, groupCode, subjectCode, subjectName,
//              credit, subjectGroup, teacherCode, teacherName }
const SEED_SUBJECTS = [
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท21101-1",
    "subjectCode": "ท21101",
    "subjectName": "ภาษาไทย 1",
    "credit": "1.5",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท21101-2",
    "subjectCode": "ท21101",
    "subjectName": "ภาษาไทย 1",
    "credit": "1.5",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค21101-1",
    "subjectCode": "ค21101",
    "subjectName": "คณิตศาสตร์ 1",
    "credit": "1.5",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ค21101-2",
    "subjectCode": "ค21101",
    "subjectName": "คณิตศาสตร์ 1",
    "credit": "1.5",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว21101-1",
    "subjectCode": "ว21101",
    "subjectName": "วิทยาศาสตร์ 1",
    "credit": "1.5",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว21101-2",
    "subjectCode": "ว21101",
    "subjectName": "วิทยาศาสตร์ 1",
    "credit": "1.5",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว21103-1",
    "subjectCode": "ว21103",
    "subjectName": "วิทยาการคำนวณ 1",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว21103-2",
    "subjectCode": "ว21103",
    "subjectName": "วิทยาการคำนวณ 1",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส21101-1",
    "subjectCode": "ส21101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 1",
    "credit": "1.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส21101-2",
    "subjectCode": "ส21101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 1",
    "credit": "1.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส21103-1",
    "subjectCode": "ส21103",
    "subjectName": "ประวัติศาสตร์ 1",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส21103-2",
    "subjectCode": "ส21103",
    "subjectName": "ประวัติศาสตร์ 1",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ21101-1",
    "subjectCode": "พ21101",
    "subjectName": "สุขศึกษา 1",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ21101-2",
    "subjectCode": "พ21101",
    "subjectName": "สุขศึกษา 1",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ21103-1",
    "subjectCode": "พ21103",
    "subjectName": "พลศึกษา 1",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ21103-2",
    "subjectCode": "พ21103",
    "subjectName": "พลศึกษา 1",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ21101-1",
    "subjectCode": "ศ21101",
    "subjectName": "ทัศนศิลป์ 1",
    "credit": "1",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ21101-2",
    "subjectCode": "ศ21101",
    "subjectName": "ทัศนศิลป์ 1",
    "credit": "1",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง21101-1",
    "subjectCode": "ง21101",
    "subjectName": "การงานอาชีพ 1",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง21101-2",
    "subjectCode": "ง21101",
    "subjectName": "การงานอาชีพ 1",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "อ21101-1",
    "subjectCode": "อ21101",
    "subjectName": "ภาษาอังกฤษ 1",
    "credit": "1.5",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "อ21101-2",
    "subjectCode": "อ21101",
    "subjectName": "ภาษาอังกฤษ 1",
    "credit": "1.5",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส20211-1",
    "subjectCode": "ส20211",
    "subjectName": "การป้องกันการทุจริต 1",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส20211-2",
    "subjectCode": "ส20211",
    "subjectName": "การป้องกันการทุจริต 1",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "จ21201-1",
    "subjectCode": "จ21201",
    "subjectName": "ภาษาจีน 1",
    "credit": "0.5",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "จ21201-2",
    "subjectCode": "จ21201",
    "subjectName": "ภาษาจีน 1",
    "credit": "0.5",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว21201-1",
    "subjectCode": "ว21201",
    "subjectName": "ทักษะกระบวนการทางวิทยาศาสตร์",
    "credit": "0.5",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว21201-2",
    "subjectCode": "ว21201",
    "subjectName": "ทักษะกระบวนการทางวิทยาศาสตร์",
    "credit": "0.5",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.1",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท21201-1",
    "subjectCode": "ท21201",
    "subjectName": "ภาษาไทยเพื่อพัฒนาการอ่าน",
    "credit": "1",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.1",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท21201-2",
    "subjectCode": "ท21201",
    "subjectName": "ภาษาไทยเพื่อพัฒนาการอ่าน",
    "credit": "1",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท22101-1",
    "subjectCode": "ท22101",
    "subjectName": "ภาษาไทย 3",
    "credit": "1.5",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท22101-2",
    "subjectCode": "ท22101",
    "subjectName": "ภาษาไทย 3",
    "credit": "1.5",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค22101-1",
    "subjectCode": "ค22101",
    "subjectName": "คณิตศาสตร์ 3",
    "credit": "1.5",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ค22101-2",
    "subjectCode": "ค22101",
    "subjectName": "คณิตศาสตร์ 3",
    "credit": "1.5",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว22101-1",
    "subjectCode": "ว22101",
    "subjectName": "วิทยาศาสตร์ 3",
    "credit": "1.5",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว22101-2",
    "subjectCode": "ว22101",
    "subjectName": "วิทยาศาสตร์ 3",
    "credit": "1.5",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว22103-1",
    "subjectCode": "ว22103",
    "subjectName": "วิทยาการคำนวณ 2",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว22103-2",
    "subjectCode": "ว22103",
    "subjectName": "วิทยาการคำนวณ 2",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส22101-1",
    "subjectCode": "ส22101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 3",
    "credit": "1.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส22101-2",
    "subjectCode": "ส22101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 3",
    "credit": "1.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส22103-1",
    "subjectCode": "ส22103",
    "subjectName": "ประวัติศาสตร์ 3",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส22103-2",
    "subjectCode": "ส22103",
    "subjectName": "ประวัติศาสตร์ 3",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ22103-1",
    "subjectCode": "พ22103",
    "subjectName": "พลศึกษา 3",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ22103-2",
    "subjectCode": "พ22103",
    "subjectName": "พลศึกษา 3",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ22101-1",
    "subjectCode": "พ22101",
    "subjectName": "สุขศึกษา 3",
    "credit": "1",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ22101-2",
    "subjectCode": "พ22101",
    "subjectName": "สุขศึกษา 3",
    "credit": "1",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ22101-1",
    "subjectCode": "ศ22101",
    "subjectName": "ศิลปะ 3",
    "credit": "1",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ22101-2",
    "subjectCode": "ศ22101",
    "subjectName": "ศิลปะ 3",
    "credit": "1",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ22101-1",
    "subjectCode": "ศ22101",
    "subjectName": "ศิลปะ 3",
    "credit": "1",
    "teacher": "653 นายสมชาติ วิโรจน์พิพัฒน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "653",
    "teacherName": "นายสมชาติ วิโรจน์พิพัฒน์"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ22101-2",
    "subjectCode": "ศ22101",
    "subjectName": "ศิลปะ 3",
    "credit": "1",
    "teacher": "653 นายสมชาติ วิโรจน์พิพัฒน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "653",
    "teacherName": "นายสมชาติ วิโรจน์พิพัฒน์"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง22101-1",
    "subjectCode": "ง22101",
    "subjectName": "การงานอาชีพ 3",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง22101-2",
    "subjectCode": "ง22101",
    "subjectName": "การงานอาชีพ 3",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "อ22101-1",
    "subjectCode": "อ22101",
    "subjectName": "ภาษาอังกฤษ 3",
    "credit": "1.5",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "อ22101-2",
    "subjectCode": "อ22101",
    "subjectName": "ภาษาอังกฤษ 3",
    "credit": "1.5",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส20213-1",
    "subjectCode": "ส20213",
    "subjectName": "การป้องกันการทุจริต 3",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส20213-2",
    "subjectCode": "ส20213",
    "subjectName": "การป้องกันการทุจริต 3",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "จ22201-1",
    "subjectCode": "จ22201",
    "subjectName": "ภาษาจีนหรรษา",
    "credit": "1",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "จ22201-2",
    "subjectCode": "จ22201",
    "subjectName": "ภาษาจีนหรรษา",
    "credit": "1",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.2",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "I20201-1",
    "subjectCode": "I20201",
    "subjectName": "การศึกษาค้นคว้าและสร้างองค์ความรู้",
    "credit": "1",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "IS",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.2",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "I20201-2",
    "subjectCode": "I20201",
    "subjectName": "การศึกษาค้นคว้าและสร้างองค์ความรู้",
    "credit": "1",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "IS",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท23101-1",
    "subjectCode": "ท23101",
    "subjectName": "ภาษาไทย 5",
    "credit": "1.5",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท23101-2",
    "subjectCode": "ท23101",
    "subjectName": "ภาษาไทย 5",
    "credit": "1.5",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค23101-1",
    "subjectCode": "ค23101",
    "subjectName": "คณิตศาสตร์ 5",
    "credit": "1.5",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ค23101-2",
    "subjectCode": "ค23101",
    "subjectName": "คณิตศาสตร์ 5",
    "credit": "1.5",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว23101-1",
    "subjectCode": "ว23101",
    "subjectName": "วิทยาศาสตร์ 5",
    "credit": "1.5",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว23101-2",
    "subjectCode": "ว23101",
    "subjectName": "วิทยาศาสตร์ 5",
    "credit": "1.5",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว23103-1",
    "subjectCode": "ว23103",
    "subjectName": "วิทยาการคำนวณ 3",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว23103-2",
    "subjectCode": "ว23103",
    "subjectName": "วิทยาการคำนวณ 3",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส23101-1",
    "subjectCode": "ส23101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 5",
    "credit": "1.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส23101-2",
    "subjectCode": "ส23101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 5",
    "credit": "1.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส23103-1",
    "subjectCode": "ส23103",
    "subjectName": "ประวัติศาสตร์ 5",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส23103-2",
    "subjectCode": "ส23103",
    "subjectName": "ประวัติศาสตร์ 5",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ23101-1",
    "subjectCode": "พ23101",
    "subjectName": "สุขศึกษาและพลศึกษา 5",
    "credit": "1",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ23101-2",
    "subjectCode": "พ23101",
    "subjectName": "สุขศึกษาและพลศึกษา 5",
    "credit": "1",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ23101-1",
    "subjectCode": "ศ23101",
    "subjectName": "ศิลปะ 5",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ23101-2",
    "subjectCode": "ศ23101",
    "subjectName": "ศิลปะ 5",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง23101-1",
    "subjectCode": "ง23101",
    "subjectName": "การงานอาชีพ 5",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง23101-2",
    "subjectCode": "ง23101",
    "subjectName": "การงานอาชีพ 5",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "อ23101-1",
    "subjectCode": "อ23101",
    "subjectName": "ภาษาอังกฤษ 5",
    "credit": "1.5",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "อ23101-2",
    "subjectCode": "อ23101",
    "subjectName": "ภาษาอังกฤษ 5",
    "credit": "1.5",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส20235-1",
    "subjectCode": "ส20235",
    "subjectName": "หน้าที่พลเมือง 5",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส20235-2",
    "subjectCode": "ส20235",
    "subjectName": "หน้าที่พลเมือง 5",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง23201-1",
    "subjectCode": "ง23201",
    "subjectName": "โครงงานอาชีพ 5",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง23201-2",
    "subjectCode": "ง23201",
    "subjectName": "โครงงานอาชีพ 5",
    "credit": "0.5",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "จ23201-1",
    "subjectCode": "จ23201",
    "subjectName": "ภาษาจีนสร้างสรรค์",
    "credit": "1",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "จ23201-2",
    "subjectCode": "จ23201",
    "subjectName": "ภาษาจีนสร้างสรรค์",
    "credit": "1",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.3",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว23201-1",
    "subjectCode": "ว23201",
    "subjectName": "ฟิสิกส์ในชีวิตประจำวัน",
    "credit": "1",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.3",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว23201-2",
    "subjectCode": "ว23201",
    "subjectName": "ฟิสิกส์ในชีวิตประจำวัน",
    "credit": "1",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท31101-1",
    "subjectCode": "ท31101",
    "subjectName": "ภาษาไทย 1",
    "credit": "1",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท31101-2",
    "subjectCode": "ท31101",
    "subjectName": "ภาษาไทย 1",
    "credit": "1",
    "teacher": "108 นางสาวนลินี กาศแสวง",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "108",
    "teacherName": "นางสาวนลินี กาศแสวง"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค31101-1",
    "subjectCode": "ค31101",
    "subjectName": "คณิตศาสตร์ 1",
    "credit": "1",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ค31101-2",
    "subjectCode": "ค31101",
    "subjectName": "คณิตศาสตร์ 1",
    "credit": "1",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว31101-1",
    "subjectCode": "ว31101",
    "subjectName": "วิทยาการคำนวณ",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว31101-2",
    "subjectCode": "ว31101",
    "subjectName": "วิทยาการคำนวณ",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส31101-1",
    "subjectCode": "ส31101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 1",
    "credit": "1",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส31101-2",
    "subjectCode": "ส31101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 1",
    "credit": "1",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส31103-1",
    "subjectCode": "ส31103",
    "subjectName": "ประวัติศาสตร์ 1",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส31103-2",
    "subjectCode": "ส31103",
    "subjectName": "ประวัติศาสตร์ 1",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ31101-1",
    "subjectCode": "พ31101",
    "subjectName": "สุขศึกษาและพลศึกษา 1",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ31101-2",
    "subjectCode": "พ31101",
    "subjectName": "สุขศึกษาและพลศึกษา 1",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ31101-1",
    "subjectCode": "ศ31101",
    "subjectName": "ดนตรี-นาฏศิลป์ 1",
    "credit": "0.5",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ31101-2",
    "subjectCode": "ศ31101",
    "subjectName": "ดนตรี-นาฏศิลป์ 1",
    "credit": "0.5",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง31101-1",
    "subjectCode": "ง31101",
    "subjectName": "การงานอาชีพ 1",
    "credit": "0.5",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง31101-2",
    "subjectCode": "ง31101",
    "subjectName": "การงานอาชีพ 1",
    "credit": "0.5",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "อ31101-1",
    "subjectCode": "อ31101",
    "subjectName": "ภาษาอังกฤษ 1",
    "credit": "1",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "อ31101-2",
    "subjectCode": "อ31101",
    "subjectName": "ภาษาอังกฤษ 1",
    "credit": "1",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส30211-1",
    "subjectCode": "ส30211",
    "subjectName": "การป้องกันการทุจริต 1",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส30211-2",
    "subjectCode": "ส30211",
    "subjectName": "การป้องกันการทุจริต 1",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว31201-1",
    "subjectCode": "ว31201",
    "subjectName": "ฟิสิกส์ 1",
    "credit": "1.5",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว31221-1",
    "subjectCode": "ว31221",
    "subjectName": "เคมี 1",
    "credit": "1.5",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว31241-1",
    "subjectCode": "ว31241",
    "subjectName": "ชีววิทยา 1",
    "credit": "1.5",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค31201-1",
    "subjectCode": "ค31201",
    "subjectName": "คณิตศาสตร์เพิ่มเติม 1",
    "credit": "1",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "จ31201-2",
    "subjectCode": "จ31201",
    "subjectName": "ภาษาจีนเพื่อการสื่อสาร 1",
    "credit": "1",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท31201-2",
    "subjectCode": "ท31201",
    "subjectName": "การแต่งคำประพันธ์",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง30201-2",
    "subjectCode": "ง30201",
    "subjectName": "การเขียนแบบเทคนิค",
    "credit": "2",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.4",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง30207-2",
    "subjectCode": "ง30207",
    "subjectName": "ศิลปะการจับจีบผ้า",
    "credit": "2",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท32101-1",
    "subjectCode": "ท32101",
    "subjectName": "ภาษาไทย 3",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท32101-2",
    "subjectCode": "ท32101",
    "subjectName": "ภาษาไทย 3",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค32101-1",
    "subjectCode": "ค32101",
    "subjectName": "คณิตศาสตร์ 3",
    "credit": "1",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ค32101-2",
    "subjectCode": "ค32101",
    "subjectName": "คณิตศาสตร์ 3",
    "credit": "1",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส32101-1",
    "subjectCode": "ส32101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 3",
    "credit": "1",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส32101-2",
    "subjectCode": "ส32101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 3",
    "credit": "1",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส32103-1",
    "subjectCode": "ส32103",
    "subjectName": "ประวัติศาสตร์ 3",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส32103-2",
    "subjectCode": "ส32103",
    "subjectName": "ประวัติศาสตร์ 3",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ32101-1",
    "subjectCode": "พ32101",
    "subjectName": "สุขศึกษาและพลศึกษา 3",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ32101-2",
    "subjectCode": "พ32101",
    "subjectName": "สุขศึกษาและพลศึกษา 3",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ32101-1",
    "subjectCode": "ศ32101",
    "subjectName": "ศิลปะ 3",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ32101-2",
    "subjectCode": "ศ32101",
    "subjectName": "ศิลปะ 3",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ32101-1",
    "subjectCode": "ศ32101",
    "subjectName": "ศิลปะ 3",
    "credit": "0.5",
    "teacher": "653 นายสมชาติ วิโรจน์พิพัฒน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "653",
    "teacherName": "นายสมชาติ วิโรจน์พิพัฒน์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ32101-2",
    "subjectCode": "ศ32101",
    "subjectName": "ศิลปะ 3",
    "credit": "0.5",
    "teacher": "653 นายสมชาติ วิโรจน์พิพัฒน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "653",
    "teacherName": "นายสมชาติ วิโรจน์พิพัฒน์"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง32101-1",
    "subjectCode": "ง32101",
    "subjectName": "การงานอาชีพ 3",
    "credit": "0.5",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง32101-2",
    "subjectCode": "ง32101",
    "subjectName": "การงานอาชีพ 3",
    "credit": "0.5",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "อ32101-1",
    "subjectCode": "อ32101",
    "subjectName": "ภาษาอังกฤษ 3",
    "credit": "1",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "อ32101-2",
    "subjectCode": "อ32101",
    "subjectName": "ภาษาอังกฤษ 3",
    "credit": "1",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส30213-2",
    "subjectCode": "ส30213",
    "subjectName": "การป้องกันการทุจริต 3",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส30213-1",
    "subjectCode": "ส30213",
    "subjectName": "การป้องกันการทุจริต 3",
    "credit": "0.5",
    "teacher": "451 นางสาวลลิตา ภู่ประเสริฐ",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "451",
    "teacherName": "นางสาวลลิตา ภู่ประเสริฐ"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว32201-1",
    "subjectCode": "ว32201",
    "subjectName": "ฟิสิกส์ 3",
    "credit": "1.5",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว32221-1",
    "subjectCode": "ว32221",
    "subjectName": "เคมี 3",
    "credit": "1.5",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว32241-1",
    "subjectCode": "ว32241",
    "subjectName": "ชีววิทยา 3",
    "credit": "1.5",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค32201-1",
    "subjectCode": "ค32201",
    "subjectName": "คณิตศาสตร์เพิ่มเติม 3",
    "credit": "1.5",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "จ32201-2",
    "subjectCode": "จ32201",
    "subjectName": "ภาษาจีนอ่าน-เขียน",
    "credit": "1.5",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "I30201-1",
    "subjectCode": "I30201",
    "subjectName": "การศึกษาค้นคว้าและสร้างองค์ความรู้",
    "credit": "1",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "IS",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "I30201-2",
    "subjectCode": "I30201",
    "subjectName": "การศึกษาค้นคว้าและสร้างองค์ความรู้",
    "credit": "1",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "IS",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท33101-1",
    "subjectCode": "ท33101",
    "subjectName": "ภาษาไทย 5",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ท33101-2",
    "subjectCode": "ท33101",
    "subjectName": "ภาษาไทย 5",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค33101-1",
    "subjectCode": "ค33101",
    "subjectName": "คณิตศาสตร์ 5",
    "credit": "1",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ค33101-2",
    "subjectCode": "ค33101",
    "subjectName": "คณิตศาสตร์ 5",
    "credit": "1",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33101-1",
    "subjectCode": "ว33101",
    "subjectName": "วิทยาศาสตร์กายภาพ (ฟิสิกส์)",
    "credit": "1",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33101-2",
    "subjectCode": "ว33101",
    "subjectName": "วิทยาศาสตร์กายภาพ (ฟิสิกส์)",
    "credit": "1",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ส33101-1",
    "subjectCode": "ส33101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 5",
    "credit": "1",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ส33101-2",
    "subjectCode": "ส33101",
    "subjectName": "สังคมศึกษา ศาสนาและวัฒนธรรม 5",
    "credit": "1",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "สังคมศึกษา ศาสนาและวัฒนธรรม",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "พ33101-1",
    "subjectCode": "พ33101",
    "subjectName": "สุขศึกษาและพลศึกษา 5",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "พ33101-2",
    "subjectCode": "พ33101",
    "subjectName": "สุขศึกษาและพลศึกษา 5",
    "credit": "0.5",
    "teacher": "503 นายพิสันต์ สายโรจน์",
    "subjectGroup": "สุขศึกษาและพลศึกษา",
    "teacherCode": "503",
    "teacherName": "นายพิสันต์ สายโรจน์"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ33101-1",
    "subjectCode": "ศ33101",
    "subjectName": "ศิลปะ 5",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ33101-2",
    "subjectCode": "ศ33101",
    "subjectName": "ศิลปะ 5",
    "credit": "0.5",
    "teacher": "404 นางสาวพิมลพรรณ ไตรรักษ์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "404",
    "teacherName": "นางสาวพิมลพรรณ ไตรรักษ์"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ33101-1",
    "subjectCode": "ศ33101",
    "subjectName": "ศิลปะ 5",
    "credit": "0.5",
    "teacher": "653 นายสมชาติ วิโรจน์พิพัฒน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "653",
    "teacherName": "นายสมชาติ วิโรจน์พิพัฒน์"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ33101-2",
    "subjectCode": "ศ33101",
    "subjectName": "ศิลปะ 5",
    "credit": "0.5",
    "teacher": "653 นายสมชาติ วิโรจน์พิพัฒน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "653",
    "teacherName": "นายสมชาติ วิโรจน์พิพัฒน์"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง33101-1",
    "subjectCode": "ง33101",
    "subjectName": "การงานอาชีพ 5",
    "credit": "0.5",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ง33101-2",
    "subjectCode": "ง33101",
    "subjectName": "การงานอาชีพ 5",
    "credit": "0.5",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "อ33101-1",
    "subjectCode": "อ33101",
    "subjectName": "ภาษาอังกฤษ 5",
    "credit": "1",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "อ33101-2",
    "subjectCode": "อ33101",
    "subjectName": "ภาษาอังกฤษ 5",
    "credit": "1",
    "teacher": "801 นางสาวชิราพร สุขเจริญ",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "801",
    "teacherName": "นางสาวชิราพร สุขเจริญ"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33201-1",
    "subjectCode": "ว33201",
    "subjectName": "ฟิสิกส์ 5",
    "credit": "1.5",
    "teacher": "313 นายพรพิพัฒน์ สุทธิธรรม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "313",
    "teacherName": "นายพรพิพัฒน์ สุทธิธรรม"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33221-1",
    "subjectCode": "ว33221",
    "subjectName": "เคมี 5",
    "credit": "1.5",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33241-1",
    "subjectCode": "ว33241",
    "subjectName": "ชีววิทยา 5",
    "credit": "1.5",
    "teacher": "314 นางสาวสุนิสา ชวนยิ้ม",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "314",
    "teacherName": "นางสาวสุนิสา ชวนยิ้ม"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33261-1",
    "subjectCode": "ว33261",
    "subjectName": "โลก ดาราศาสตร์ และอวกาศ 5",
    "credit": "0.5",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค33201-1",
    "subjectCode": "ค33201",
    "subjectName": "คณิตศาสตร์เพิ่มเติม 5",
    "credit": "1.5",
    "teacher": "203 นางสาวสมใจ จันทรงกรด",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "203",
    "teacherName": "นางสาวสมใจ จันทรงกรด"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว32101-1",
    "subjectCode": "ว32101",
    "subjectName": "วิทยาศาสตร์กายภาพ (เคมี)",
    "credit": "1",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว32101-2",
    "subjectCode": "ว32101",
    "subjectName": "วิทยาศาสตร์กายภาพ (เคมี)",
    "credit": "1",
    "teacher": "312 นายกิตติศักดิ์ รัตนชัย",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "312",
    "teacherName": "นายกิตติศักดิ์ รัตนชัย"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท32201-1",
    "subjectCode": "ท32201",
    "subjectName": "เรียงร้อยถ้อยอักษร",
    "credit": "0.5",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง30203-1",
    "subjectCode": "ง30203",
    "subjectName": "การติดตั้งไฟฟ้าในอาคาร",
    "credit": "2",
    "teacher": "710 นายศรายุทธ แสนเกียง",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "710",
    "teacherName": "นายศรายุทธ แสนเกียง"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ง30209-1",
    "subjectCode": "ง30209",
    "subjectName": "การประกอบอาหารไทย",
    "credit": "2",
    "teacher": "709 นางสาวนฤมล มะลิเทิน",
    "subjectGroup": "การงานอาชีพ",
    "teacherCode": "709",
    "teacherName": "นางสาวนฤมล มะลิเทิน"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33103-1",
    "subjectCode": "ว33103",
    "subjectName": "วิทยาการคำนวณ 3",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.6",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว33103-2",
    "subjectCode": "ว33103",
    "subjectName": "วิทยาการคำนวณ 3",
    "credit": "1",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ศ33101-1",
    "subjectCode": "ศ33101",
    "subjectName": "ศิลปะ 5",
    "credit": "0.5",
    "teacher": "653 นายสมชาติ วิโรจน์พิพัฒน์",
    "subjectGroup": "ศิลปะ",
    "teacherCode": "653",
    "teacherName": "นายสมชาติ วิโรจน์พิพัฒน์"
  },
  {
    "level": "ม.6",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "อ33209-1",
    "subjectCode": "อ33209",
    "subjectName": "ภาษาอังกฤษเพิ่มเติม 5",
    "credit": "0.5",
    "teacher": "806 นางสาวศิริวรรณ พานตะสี",
    "subjectGroup": "ภาษาต่างประเทศ",
    "teacherCode": "806",
    "teacherName": "นางสาวศิริวรรณ พานตะสี"
  },
  {
    "level": "ม.5",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ว30209-1",
    "subjectCode": "ว30209",
    "subjectName": "ปัญญาประดิษฐ์",
    "credit": "0.5",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.5",
    "groupNo": "2",
    "year": "2569",
    "term": "1",
    "groupCode": "ว30209-2",
    "subjectCode": "ว30209",
    "subjectName": "ปัญญาประดิษฐ์",
    "credit": "0.5",
    "teacher": "311 นางภัทรหทัย ทองอยู่",
    "subjectGroup": "วิทยาศาสตร์และเทคโนโลยี",
    "teacherCode": "311",
    "teacherName": "นางภัทรหทัย ทองอยู่"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ท30201-1",
    "subjectCode": "ท30201",
    "subjectName": "วรรณกรรมเพลงพื้นบ้าน",
    "credit": "1",
    "teacher": "104 นายกิตติธัช สีหะวงษ์",
    "subjectGroup": "ภาษาไทย",
    "teacherCode": "104",
    "teacherName": "นายกิตติธัช สีหะวงษ์"
  },
  {
    "level": "ม.4",
    "groupNo": "1",
    "year": "2569",
    "term": "1",
    "groupCode": "ค30201-1",
    "subjectCode": "ค30201",
    "subjectName": "คณิตศาสตร์การเงิน",
    "credit": "1",
    "teacher": "210 นายอชิตพล บุณรัตน์",
    "subjectGroup": "คณิตศาสตร์",
    "teacherCode": "210",
    "teacherName": "นายอชิตพล บุณรัตน์"
  }
];

// รายชื่อหัวหน้ากลุ่มสาระการเรียนรู้ (ใช้พิมพ์ในช่องลงลายมือชื่อของ ปพ.5)
const DEPT_HEADS = {
  "ภาษาไทย": "นายกิตติธัช สีหะวงษ์",
  "คณิตศาสตร์": "นางสาวสมใจ จันทรงกรด",
  "วิทยาศาสตร์และเทคโนโลยี": "นางสาวสุนิสา ชวนยิ้ม",
  "สุขศึกษาและพลศึกษา": "นายพิสันต์ สายโรจน์",
  "สังคมศึกษา ศาสนาและวัฒนธรรม": "นางสาวพิมลพรรณ ไตรรักษ์",
  "ศิลปะ": "นางสาวนลินี กาศแสวง",
  "การงานอาชีพ": "นางสาวนฤมล มะลิเทิน",
  "ภาษาต่างประเทศ": "นางสาวศิริวรรณ พานตะสี",
  "IS": "นายกิตติศักดิ์ รัตนชัย"
};

// ข้อมูลผู้บริหาร / งานทะเบียนวัดผล
const SCHOOL_INFO = {
  schoolName: "โรงเรียนวังโพรงพิทยาคม",
  schoolNameFull: "โรงเรียนวังโพรงพิทยาคม อำเภอเนินมะปราง จังหวัดพิษณุโลก",
  eduArea: "สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาพิษณุโลก อุตรดิตถ์",
  registrarHead: "นายกิตติศักดิ์ รัตนชัย",
  director: "นางสาวสมใจ จันทรงกรด",
  directorTitle: "ครูชำนาญการพิเศษ รักษาการในตำแหน่ง ผู้อำนวยการโรงเรียนวังโพรงพิทยาคม",
  logoUrl: "https://img2.pic.in.th/pic/_-removebg-previewd98d6d3aba068e49.png",
  footerDevBy: "กลุ่มบริหารงานวิชาการ",
  footerDevLink: "https://www.facebook.com/kittiikr/",
  footerYear: "2025"
};

// ตัวเลือกกลุ่มสาระการเรียนรู้ (8 กลุ่มหลัก ตามหลักสูตร)
const SUBJECT_GROUPS = [
  "ภาษาไทย",
  "คณิตศาสตร์",
  "วิทยาศาสตร์และเทคโนโลยี",
  "สังคมศึกษา ศาสนาและวัฒนธรรม",
  "สุขศึกษาและพลศึกษา",
  "ศิลปะ",
  "การงานอาชีพ",
  "ภาษาต่างประเทศ"
];

// ระดับชั้นทั้งหมด
const LEVELS = ["ม.1", "ม.2", "ม.3", "ม.4", "ม.5", "ม.6"];

// คอลัมน์ผลการเรียน (มาตราส่วน 8 ระดับ + ร,มส,ผ,มผ) เรียงตามเอกสารต้นฉบับของโรงเรียน
const GRADE_COLS = ["0","1","1.5","2","2.5","3","3.5","4","ร","มส","ผ","มผ"];

// ค่าคะแนนเป็นตัวเลข (ใช้คำนวณ X̄ และ SD) — ร,มส,ผ,มผ ไม่มีค่าคะแนน
const GRADE_POINTS = {"4":4,"3.5":3.5,"3":3,"2.5":2.5,"2":2,"1.5":1.5,"1":1,"0":0};

// ระดับคุณลักษณะอันพึงประสงค์ / การอ่านคิดวิเคราะห์และเขียน
const RATING_COLS = ["3","2","1","0"];
